selector:
  name: '&eServer Selector'
  material: 'COMPASS'
  lore:
    - '&eSelect a server to go to'
    - '&7Right-Click to open up the server selection menu'
inventory:
  removeDuplicates: true
  giveOnJoin: true