name: ServerSelector
main: me.darrionat.serverselector.ServerSelectorPlugin
version: 1.0.1
description: Select what Bungeed server to travel to
api-version: 1.13

commands:
  serverselector:
    aliases: [ ss ]
    usage: /<command> help